server:
  port: ${APP_PORT}
spring:
  application:
    name: comments
  datasource:
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE_NAME}
    username: ${PG_USER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true